name: Generate Email/Push Queues

on:
  workflow_dispatch:
    inputs:
      site:
        type: choice
        description: Which site?
        options:
          - f1
          - f2
          - f3
          - fe
          - indycar
          - motogp
          - f1-academy
  workflow_call:
    inputs:
      site:
        required: true
        type: string
    secrets:
      FIREBASE_CREDENTIALS:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      SITE: ${{ github.event.inputs.site || inputs.site }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '22'

      - name: Site Selection
        run: |
          echo "${{ env.SITE }}"

      - name: Cache node modules
        uses: actions/cache@v4
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install Dependencies
        run: |
          npm i firebase-admin
          npm i dayjs

      - name: Generate Specific Queues
        run: |
          sudo -E node build/generate-queues.mjs ${{env.SITE}}
        env:
          FIREBASE_CREDENTIALS: ${{ secrets.FIREBASE_CREDENTIALS }}
